# Generated by Django 3.2.8 on 2021-10-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20211018_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city_uz',
            field=models.CharField(max_length=30, verbose_name='Город (УЗБ)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='landmark_uz',
            field=models.CharField(blank=True, max_length=40, verbose_name='Ориентир (УЗБ)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_uz',
            field=models.CharField(max_length=30, verbose_name='Улица (УЗБ)'),
        ),
    ]
