# Generated by Django 3.2.8 on 2021-10-12 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('title_uz', models.CharField(max_length=150, verbose_name='Название (УЗБ)')),
                ('img', models.ImageField(upload_to='media', verbose_name='Картинка')),
                ('slug', models.CharField(blank=True, max_length=300, verbose_name='URL (Необязательно)')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='MetaTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=300, verbose_name='Title (УЗБ)')),
                ('keywords', models.TextField(verbose_name='Keywords (Через запятую/Предложением)')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Мета тег',
                'verbose_name_plural': 'Мета теги',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название товара')),
                ('name_uz', models.CharField(max_length=300, verbose_name='Название товара (УЗБ)')),
                ('model', models.CharField(blank=True, max_length=300, verbose_name='Модель товара')),
                ('slug', models.CharField(blank=True, max_length=300, verbose_name='URL (Необязательно)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.categories')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок описания')),
                ('title_uz', models.CharField(max_length=200, verbose_name='Заголовок описания (УЗБ)')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('description_uz', models.TextField(verbose_name='Описание товара (УЗБ)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.product')),
            ],
            options={
                'verbose_name': 'Описание',
                'verbose_name_plural': 'Описания',
            },
        ),
    ]
