# Generated by Django 3.2.8 on 2021-10-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='Картинка'),
        ),
    ]
