# Generated by Django 3.2.8 on 2021-10-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefits',
            name='how_many_reviews',
            field=models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Более скольки отзывов?'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='how_many_sold',
            field=models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Сколько насосов продано?'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='how_time_service_working',
            field=models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Сколько лет на рынке?'),
        ),
    ]
